# Generated by Django 5.0.3 on 2024-05-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_community_exam_exam_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
