# Generated by Django 5.0.3 on 2024-04-20 16:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_content', models.TextField(max_length=1000)),
                ('post_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_creators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
