# Generated by Django 5.0.3 on 2024-05-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_assignmentpost_studentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='post_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
