# Generated by Django 5.0.3 on 2024-05-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_communitypost_post_image_communitypost_post_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='post_image',
        ),
        migrations.AddField(
            model_name='communitypost',
            name='post_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
