# Generated by Django 5.0.3 on 2024-05-18 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_postcomment_communitypost_comments_postlike_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='commented_posts', through='community.PostComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', through='community.PostLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
