# Generated by Django 5.0.3 on 2024-05-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_postcomment_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='parent_comment',
        ),
    ]
