# Generated by Django 5.0.3 on 2024-04-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userabout',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userbackgroundphoto',
            field=models.ImageField(blank=True, default='static/images/resources/default_user_background.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userprofilephoto',
            field=models.ImageField(default='static/images/resources/default_user_pp.png', upload_to='images/'),
        ),
    ]
