# Generated by Django 5.0.3 on 2024-04-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_customuser_userabout_customuser_userbackgroundphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userbackgroundphoto',
            field=models.ImageField(blank=True, default='images/default_user_background.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userprofilephoto',
            field=models.ImageField(default='images/default_user_pp.png', upload_to='images/'),
        ),
    ]
