# Generated by Django 5.0.3 on 2024-04-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_alter_customuser_userbackgroundphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userprofilephoto',
            field=models.ImageField(blank=True, default='images/default_user_pp.png', upload_to='images/'),
        ),
    ]
